export enum LegislativeLevel {
  DPR_RI = 'DPR_RI',
  DPD_RI = 'DPD_RI',
  MPR_RI = 'MPR_RI',
  DPRD_PROVINSI = 'DPRD_PROVINSI',
  DPRD_KABUPATEN_KOTA = 'DPRD_KABUPATEN_KOTA',
  KEPALA_DAERAH_GUBERNUR = 'KEPALA_DAERAH_GUBERNUR',
  KEPALA_DAERAH_WALIKOTA_BUPATI = 'KEPALA_DAERAH_WALIKOTA_BUPATI',
  PEJABAT_BIROKRAT_DIRJEN_SEKJEN_OPD = 'PEJABAT_BIROKRAT_DIRJEN_SEKJEN_OPD',
  PIMPINAN_LEMBAGA_REKTOR_SWASTA = 'PIMPINAN_LEMBAGA_REKTOR_SWASTA',
}

export type PublicOfficeRole = LegislativeLevel;
export const PublicOfficeRole = LegislativeLevel;

export enum SuperadminRole {
  SUPERADMIN = 'SUPERADMIN',
  SUPPORT_OPERATOR = 'SUPPORT_OPERATOR',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
}

export enum TenantAccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum SubscriptionStatus {
  INACTIVE = 'INACTIVE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  ACTIVE = 'ACTIVE',
  GRACE_PERIOD = 'GRACE_PERIOD',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum PlanTier {
  STARTER = 'STARTER',
  PRO = 'PRO',
  VIP = 'VIP',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SETTLEMENT = 'SETTLEMENT',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
}

export enum ContentStatus {
  GENERATING = 'GENERATING',
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  UNPUBLISHED = 'UNPUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum AssetType {
  DALLE_POSTER = 'DALLE_POSTER',
  INFOGRAPHIC_PNG = 'INFOGRAPHIC_PNG',
  HEADER_IMAGE = 'HEADER_IMAGE',
}

export enum DocType {
  PERDA = 'PERDA',
  PERBUP = 'PERBUP',
  APBD = 'APBD',
  RPJMD = 'RPJMD',
  BPS_STATISTIC = 'BPS_STATISTIC',
  NOTULA_SIDANG = 'NOTULA_SIDANG',
}

export enum LegalStatus {
  BERLAKU = 'BERLAKU',
  DICABUT = 'DICABUT',
  DIUJI_MK = 'DIUJI_MK',
}

export enum SocialPlatform {
  INSTAGRAM = 'INSTAGRAM',
  X_TWITTER = 'X_TWITTER',
  TIKTOK = 'TIKTOK',
  YOUTUBE = 'YOUTUBE',
  WHATSAPP = 'WHATSAPP',
}

export enum FeedbackStatus {
  RECEIVED = 'RECEIVED',
  VERIFIED = 'VERIFIED',
  RESPONDED = 'RESPONDED',
  ARCHIVED = 'ARCHIVED',
}

export enum IssueCategory {
  INFRASTRUKTUR = 'INFRASTRUKTUR',
  PERTANIAN = 'PERTANIAN',
  PENDIDIKAN = 'PENDIDIKAN',
  KESEHATAN = 'KESEHATAN',
  BANSOS_UMKM = 'BANSOS_UMKM',
  LAINNYA = 'LAINNYA',
}

export enum CommentStatus {
  PUBLISHED = 'PUBLISHED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  HIDDEN = 'HIDDEN',
  FLAGGED_SPAM = 'FLAGGED_SPAM',
}

export enum CustomDomainStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
}

export enum ReconciliationStatus {
  UNRECONCILED = 'UNRECONCILED',
  MATCHED = 'MATCHED',
  DISCREPANCY = 'DISCREPANCY',
}

export enum ReconciliationBatchStatus {
  PROCESSING = 'PROCESSING',
  BALANCED = 'BALANCED',
  DISCREPANCY_DETECTED = 'DISCREPANCY_DETECTED',
  RESOLVED = 'RESOLVED',
}

export enum DiscrepancyType {
  STATUS_MISMATCH = 'STATUS_MISMATCH',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
  MISSING_IN_INTERNAL = 'MISSING_IN_INTERNAL',
  MISSING_IN_GATEWAY = 'MISSING_IN_GATEWAY',
  FEE_MISMATCH = 'FEE_MISMATCH',
}

export enum DiscrepancyResolutionStatus {
  UNRESOLVED = 'UNRESOLVED',
  AUTO_RESOLVED = 'AUTO_RESOLVED',
  MANUALLY_RESOLVED = 'MANUALLY_RESOLVED',
  IGNORED = 'IGNORED',
}



